export const SET_WEATHER = 'SET_WEATHER';

export const CLEAR_WEATHER = 'CLEAR_WEATHER';

export const START_WEATHER_LOADING = 'START_WEATHER_LOADING';

export const COMPLETE_WEATHER_LOADING = 'COMPLETE_WEATHER_LOADING';